const configs={
  conservative:{label:'보수형',base:{ret:2.4,bench:1.8,dd:-3.2,vol:8.6,win:58}},
  balanced:{label:'균형형',base:{ret:4.8,bench:3.1,dd:-6.4,vol:13.2,win:62}},
  aggressive:{label:'공격형',base:{ret:7.1,bench:3.1,dd:-11.8,vol:21.7,win:55}},
};
const periods={
  '3m':{label:'3개월',range:'2026.05.26~08.25',factor:.55,months:['2026.06','2026.07','2026.08']},
  '6m':{label:'6개월',range:'2026.02.26~08.25',factor:1,months:['2026.04','2026.05','2026.06','2026.07','2026.08']},
  '1y':{label:'1년',range:'2025.08.26~2026.08.25',factor:1.75,months:['2026.04','2026.05','2026.06','2026.07','2026.08']},
};
let strategy='balanced';let period='6m';let selectedIndex=0;
const list=document.querySelector('#resultList');
const fmt=value=>`${value>=0?'+':''}${value.toFixed(1)}%`;
function metrics(){const config=configs[strategy];const term=periods[period];return{ret:config.base.ret*term.factor,bench:config.base.bench*term.factor,dd:config.base.dd*(period==='3m'?.72:period==='1y'?1.35:1),vol:config.base.vol*(period==='3m'?.9:period==='1y'?1.08:1),win:Math.max(40,config.base.win+(period==='3m'?-3:period==='1y'?2:0))};}
function rows(){const term=periods[period];const m=metrics();return term.months.map((month,index)=>{const wave=[.34,-.16,.27,.08,.41][index];const portfolio=Number((m.ret/term.months.length+wave*(strategy==='aggressive'?2:1)).toFixed(1));const benchmark=Number((m.bench/term.months.length+[.12,-.08,.15,.04,.17][index]).toFixed(1));const drawdown=Number((-Math.abs(wave)*(Math.abs(m.dd)/2.2)-.4).toFixed(1));return{month,portfolio,benchmark,excess:Number((portfolio-benchmark).toFixed(1)),drawdown,state:portfolio>=benchmark?'초과':'미달'};});}
function setFacts(target,entries){document.querySelector(target).replaceChildren(...entries.map(([key,value])=>{const row=document.createElement('div');const dt=document.createElement('dt');const dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);return row;}));}
function renderInspector(row){const config=configs[strategy];const term=periods[period];const m=metrics();document.querySelector('#detailTitle').textContent=`${config.label} · ${row.month}`;document.querySelector('#detailSummary').textContent=`${term.label} 화면용 검증 중 선택 월 결과입니다. 실제 과거 시세 계산이 아닙니다.`;setFacts('#calculationFacts',[['월 수익률','(월말-월초)÷월초'],['선택 월',fmt(row.portfolio)],['수수료','매매금액 0.015% 가정'],['세금·슬리피지','0.18%·0.10% 가정']]);setFacts('#riskFacts',[['최대 낙폭',fmt(m.dd)],['선택 월 낙폭',fmt(row.drawdown)],['연환산 변동성',`${m.vol.toFixed(1)}%`],['데이터','고정 배열·KRW 예시']]);}
function selectRow(index){selectedIndex=index;list.querySelectorAll('.result-row').forEach((button,i)=>{const selected=i===index;button.classList.toggle('selected',selected);button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;});renderInspector(rows()[index]);}
function render(){const config=configs[strategy];const term=periods[period];const m=metrics();document.querySelector('#summaryTitle').textContent=`${config.label} · ${term.label}`;document.querySelector('#metricPeriod').textContent=term.range;document.querySelector('#metricReturn').textContent=fmt(m.ret);document.querySelector('#metricBenchmark').textContent=fmt(m.bench);document.querySelector('#metricDrawdown').textContent=fmt(m.dd);document.querySelector('#metricVolatility').textContent=`${m.vol.toFixed(1)}%`;document.querySelector('#metricWinRate').textContent=`${m.win}%`;const data=rows();selectedIndex=Math.min(selectedIndex,data.length-1);list.replaceChildren(...data.map((row,index)=>{const button=document.createElement('button');button.type='button';button.className='result-row';button.setAttribute('role','option');button.innerHTML=`<span><strong>${row.month}</strong><small>월말 고정 예시</small></span><span class="${row.portfolio>=0?'positive':'negative'}">${fmt(row.portfolio)}</span><span>${fmt(row.benchmark)}</span><span class="${row.excess>=0?'positive':'negative'}">${fmt(row.excess)}</span><span class="negative">${fmt(row.drawdown)}</span><span class="result-state">${row.state}</span>`;button.addEventListener('click',()=>selectRow(index));return button;}));selectRow(selectedIndex);}
function bind(selector,key){document.querySelectorAll(selector).forEach(button=>button.addEventListener('click',()=>{button.parentElement.querySelectorAll('button').forEach(item=>{const active=item===button;item.classList.toggle('selected',active);item.setAttribute('aria-pressed',String(active));});if(key==='period')period=button.dataset.period;else strategy=button.dataset.strategy;selectedIndex=0;render();}));}
bind('#periodFilters button','period');bind('#strategyFilters button','strategy');render();
