const current=[
  {key:'cash',name:'현금성 자산',ticker:'KRW',weight:18.4},
  {key:'market',name:'KODEX 200',ticker:'069500',weight:31.6},
  {key:'samsung',name:'삼성전자',ticker:'005930',weight:7.2},
  {key:'sk',name:'SK하이닉스',ticker:'000660',weight:22.8},
  {key:'naver',name:'NAVER',ticker:'035420',weight:20.0},
];
const strategies={
  conservative:{label:'보수형',expectedReturn:'연 +4.2%',volatility:'8.6%',drawdown:'-5.1%',targets:{cash:30,market:34,samsung:7,sk:15,naver:14}},
  balanced:{label:'균형형',expectedReturn:'연 +6.8%',volatility:'13.2%',drawdown:'-8.4%',targets:{cash:18,market:32,samsung:8,sk:22,naver:20}},
  aggressive:{label:'공격형',expectedReturn:'연 +9.4%',volatility:'21.7%',drawdown:'-14.8%',targets:{cash:10,market:24,samsung:10,sk:31,naver:25}},
};
let strategy='balanced';let selectedIndex=0;
const allocationList=document.querySelector('#allocationList');const proposalList=document.querySelector('#proposalList');
const signed=value=>`${value>0?'+':''}${value.toFixed(1)}%p`;
function proposals(){const targets=strategies[strategy].targets;return current.filter(asset=>Math.abs(targets[asset.key]-asset.weight)>=.1).map(asset=>{const delta=Number((targets[asset.key]-asset.weight).toFixed(1));const amount=Math.round(Math.abs(delta)*1301800/1000)*1000;return{...asset,target:targets[asset.key],delta,direction:delta>0?'비중 확대':'비중 축소',amount:`약 ${amount.toLocaleString('ko-KR')}원`,policy:asset.key==='samsung'&&targets[asset.key]>=8?'한도 경계':'화면상 범위',source:'가격·잔고 고정 예시',effect:`${asset.name} 비중을 ${asset.weight.toFixed(1)}%에서 ${targets[asset.key].toFixed(1)}%로 조정하는 가상 제안입니다.`};});}
function setFacts(selector,entries){document.querySelector(selector).replaceChildren(...entries.map(([key,value])=>{const row=document.createElement('div');const dt=document.createElement('dt');const dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);return row;}));}
function renderInspector(item){const plan=strategies[strategy];document.querySelector('#detailTitle').textContent=`${item.name} · ${item.direction}`;document.querySelector('#detailSummary').textContent=item.effect;setFacts('#effectFacts',[['현재 비중',`${item.weight.toFixed(1)}%`],['목표 비중',`${item.target.toFixed(1)}%`],['비중 변화',signed(item.delta)],['예상 금액',item.amount]]);setFacts('#policyFacts',[['전략',plan.label],['종목 한도',item.policy],['최소 현금',plan.targets.cash>=15?'충족 예시':'미달 경고'],['승인 상태','사용자 확인 전']]);setFacts('#riskFacts',[['예상 변동성',plan.volatility],['예상 최대 낙폭',plan.drawdown],['출처 상태',item.source],['외부 요청','0건']]);}
function selectProposal(index){selectedIndex=index;proposalList.querySelectorAll('.proposal-row').forEach((button,i)=>{const selected=i===index;button.classList.toggle('selected',selected);button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;});renderInspector(proposals()[index]);}
function render(){const plan=strategies[strategy];document.querySelector('#summaryTitle').textContent=`${plan.label} 목표안`;document.querySelector('#expectedReturn').textContent=plan.expectedReturn;document.querySelector('#expectedVolatility').textContent=plan.volatility;document.querySelector('#expectedDrawdown').textContent=plan.drawdown;document.querySelector('#targetCash').textContent=`${plan.targets.cash.toFixed(1)}%`;allocationList.replaceChildren(...current.map(asset=>{const target=plan.targets[asset.key];const delta=target-asset.weight;const card=document.createElement('article');card.className='allocation-card';card.innerHTML=`<strong>${asset.name}</strong><small>${asset.ticker} · 가상 잔고</small><div class="weight-pair"><div><span>현재</span><b>${asset.weight.toFixed(1)}%</b></div><div><span>목표</span><b>${target.toFixed(1)}%</b></div></div><div class="weight-track"><i style="width:${target}%"></i></div><em class="${delta>0?'up':delta<0?'down':''}">${signed(delta)}</em>`;return card;}));const items=proposals();document.querySelector('#proposalCount').textContent=`${items.length}건 · 실제 주문 생성 없음`;selectedIndex=Math.min(selectedIndex,items.length-1);proposalList.replaceChildren(...items.map((item,index)=>{const button=document.createElement('button');button.type='button';button.className='proposal-row';button.setAttribute('role','option');button.innerHTML=`<span><strong>${item.name}</strong><small>${item.ticker} · 화면용</small></span><span class="${item.delta>0?'buy':'sell'}">${item.delta>0?'확대':'축소'}</span><span>${signed(item.delta)}</span><span>${item.amount}</span><span class="policy-state">${item.policy}</span>`;button.addEventListener('click',()=>selectProposal(index));return button;}));selectProposal(selectedIndex);}
document.querySelectorAll('#strategyFilters button').forEach(button=>button.addEventListener('click',()=>{button.parentElement.querySelectorAll('button').forEach(item=>{const active=item===button;item.classList.toggle('selected',active);item.setAttribute('aria-pressed',String(active));});strategy=button.dataset.strategy;selectedIndex=0;render();}));
render();
