const assets=[
  {key:'cash',name:'현금성 자산',ticker:'KRW',weight:18.4},
  {key:'market',name:'KODEX 200',ticker:'069500',weight:31.6},
  {key:'samsung',name:'삼성전자',ticker:'005930',weight:7.2},
  {key:'sk',name:'SK하이닉스',ticker:'000660',weight:22.8},
  {key:'naver',name:'NAVER',ticker:'035420',weight:20.0},
];
const scenarios={
  rates:{label:'금리 급등',copy:'채권·성장주 압박을 화면용 고정 충격값으로 점검합니다.',loss:-6.8,drawdown:-9.4,cash:'보통',alerts:3,shock:{cash:.2,market:-4.8,samsung:-6.2,sk:-8.4,naver:-10.6},assumption:'기준금리 +100bp, 성장주 할인율 상승',weak:'NAVER·반도체 비중',policy:'현금 18.4%로 방어 여력 보통',responses:['현금 목표 22% 검토','성장주 비중 축소 후보','승인 대기 전 위험 알림 확인']},
  chips:{label:'반도체 급락',copy:'반도체 업종 동반 하락을 고정 손실 예시로 비교합니다.',loss:-8.9,drawdown:-12.7,cash:'취약',alerts:4,shock:{cash:.1,market:-5.4,samsung:-13.8,sk:-16.2,naver:-4.1},assumption:'반도체 업종 -15% 동시 충격',weak:'삼성전자·SK하이닉스 집중',policy:'종목·업종 집중 경계 예시',responses:['반도체 합산 비중 경고','KODEX 200 대체 검토','추가 매수 차단 후보']},
  fx:{label:'환율 충격',copy:'원화 약세와 수입 비용 압박을 화면용으로 점검합니다.',loss:-4.6,drawdown:-6.8,cash:'양호',alerts:2,shock:{cash:.0,market:-3.2,samsung:-2.8,sk:-3.6,naver:-8.5},assumption:'USD/KRW +7%, 외국인 수급 둔화',weak:'내수·플랫폼 민감도',policy:'외부 환율 데이터 미연결',responses:['환율 민감 종목 표시','현금 유지 후보','데이터 연결 상태 확인']},
  liquidity:{label:'유동성 경색',copy:'거래대금 축소와 스프레드 확대를 고정 가정으로 봅니다.',loss:-7.3,drawdown:-10.5,cash:'보통',alerts:3,shock:{cash:.0,market:-6.8,samsung:-5.5,sk:-9.1,naver:-12.4},assumption:'스프레드 확대, 체결 비용 증가 가정',weak:'변동성 높은 종목',policy:'슬리피지 단순 가정',responses:['시장가 금지 유지','지정가 폭 축소 후보','승인 만료 시간 단축 검토']},
};
let scenario='rates';let selectedAsset=0;let selectedResponse=0;
const impactList=document.querySelector('#impactList');const responseList=document.querySelector('#responseList');
const fmt=value=>`${value>0?'+':''}${value.toFixed(1)}%`;
function rows(){const data=scenarios[scenario];return assets.map(asset=>{const shock=data.shock[asset.key];const contribution=Number((asset.weight*shock/100).toFixed(2));return{...asset,shock,contribution,state:shock<=-10?'높음':shock<=-6?'주의':'관리'};});}
function setFacts(selector,entries){document.querySelector(selector).replaceChildren(...entries.map(([key,value])=>{const row=document.createElement('div');const dt=document.createElement('dt');const dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);return row;}));}
function renderInspector(){const data=scenarios[scenario];const asset=rows()[selectedAsset];const response=data.responses[selectedResponse];document.querySelector('#detailTitle').textContent=`${data.label} · ${asset.name}`;document.querySelector('#detailSummary').textContent=`${asset.name}의 화면용 충격률은 ${fmt(asset.shock)}이며 대응 후보는 '${response}'입니다.`;setFacts('#scenarioFacts',[['시나리오',data.label],['충격 가정',data.assumption],['예상 손실',fmt(data.loss)],['경보 수',`${data.alerts}건`]]);setFacts('#weaknessFacts',[['선택 자산',asset.name],['포트폴리오 비중',`${asset.weight.toFixed(1)}%`],['충격률',fmt(asset.shock)],['손익 영향',`${asset.contribution.toFixed(2)}%p`]]);setFacts('#policyFacts',[['정책 경계',data.policy],['데이터 상태','고정 예시·미연결'],['실제 계좌','미반영'],['외부 요청','0건']]);}
function selectAsset(index){selectedAsset=index;impactList.querySelectorAll('.impact-row').forEach((button,i)=>{const selected=i===index;button.classList.toggle('selected',selected);button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;});renderInspector();}
function selectResponse(index){selectedResponse=index;responseList.querySelectorAll('.response-card').forEach((button,i)=>{const selected=i===index;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});renderInspector();}
function render(){const data=scenarios[scenario];document.querySelector('#summaryTitle').textContent=`${data.label} 시나리오`;document.querySelector('#summaryCopy').textContent=data.copy;document.querySelector('#lossMetric').textContent=fmt(data.loss);document.querySelector('#drawdownMetric').textContent=fmt(data.drawdown);document.querySelector('#cashMetric').textContent=data.cash;document.querySelector('#alertMetric').textContent=`${data.alerts}건`;const impactRows=rows();selectedAsset=Math.min(selectedAsset,impactRows.length-1);impactList.replaceChildren(...impactRows.map((asset,index)=>{const button=document.createElement('button');button.type='button';button.className='impact-row';button.setAttribute('role','option');button.innerHTML=`<span><strong>${asset.name}</strong><small>${asset.ticker} · 화면용 비중</small></span><span>${asset.weight.toFixed(1)}%</span><span class="${asset.shock<0?'negative':'stable'}">${fmt(asset.shock)}</span><span class="${asset.contribution<0?'negative':'stable'}">${asset.contribution.toFixed(2)}%p</span><span class="impact-state">${asset.state}</span>`;button.addEventListener('click',()=>selectAsset(index));return button;}));document.querySelector('#responseCount').textContent=`${data.responses.length}건 · 실행 없음`;selectedResponse=Math.min(selectedResponse,data.responses.length-1);responseList.replaceChildren(...data.responses.map((item,index)=>{const button=document.createElement('button');button.type='button';button.className='response-card';button.setAttribute('aria-pressed',String(index===selectedResponse));button.innerHTML=`<strong>${item}</strong><span>${data.label} 대응 후보</span><small>실행이 아닌 화면용 검토 항목입니다. 사용자 승인 전 어떤 주문도 생성하지 않습니다.</small>`;button.addEventListener('click',()=>selectResponse(index));return button;}));selectAsset(selectedAsset);selectResponse(selectedResponse);}
document.querySelectorAll('#scenarioFilters button').forEach(button=>button.addEventListener('click',()=>{button.parentElement.querySelectorAll('button').forEach(item=>{const active=item===button;item.classList.toggle('selected',active);item.setAttribute('aria-pressed',String(active));});scenario=button.dataset.scenario;selectedAsset=0;selectedResponse=0;render();}));
render();
